### ISSUE TITLE
Please update for version 5

### ISSUE THREAD

**Issue by charris-crs** [VeeamHub/powershell#135]
**Describe the bug**

The command Get-VBOOrganizationMailbox on line26 has been deprecated and replaced by Get-VBOOrganizationUser and VBOBackupItem instead.

Is there an update to this script to reflect these changes?
Or is there any where I can get assistance to try and make it work
e.g. Would this work?
# O365 PowerShell call - Return all Exchange Mailboxes
Try
{
    $MailBoxes = Get-VBOOrganizationUser -Organization $org 
}
Catch
{
    Write-Host "No mailboxes defined!"
    Exit 1
}

# Exchange Powershell call - Return all Exchange Mailbox under the Organisational Unit $OrgUnit defined above.
Try
{
    $mbxs = Get-Mailbox -OrganizationalUnit $OrgUnit -ResultSize Unlimited
}
Catch
{
    Write-Host "No mailboxes within $OrgUnit defined!"
    Exit 1
}

Many Thanks

**Comment by carceneaux** [comment]
Hi @charris-crs,

Which script in particular are you referring to?

**Comment by carceneaux** [comment]
Script in question is: https://github.com/VeeamHub/powershell/blob/master/VBO-CreateJobByOrg/Add_VBO_Job.ps1

Corresponding forum thread: https://forums.veeam.com/veeam-backup-for-microsoft-office-365-f53/create-a-backup-job-by-ou-t76884.html
