### ISSUE TITLE
BR-DataIntegrationAPIModule.psm1

### ISSUE THREAD

**Issue by Ti360** [VeeamHub/powershell#181]
Hello, 

Long story short, I have a VBR in aws and one all-in-one (hyper-v, On host proxy, On host repository) server per site (20+ sites). I wondered if there was a way to tell the script to use the server where the job was running instead of using get-random. For example, I added the PS file to a test job in Toronto/Canada, and get-random attached the drive to a veeam proxy in Dallas/Texas. I was about to test using location tagging, but I did not plan to use that feature in the future.

It was only a 50 GB drive, but I am targeting bigger than that over a weekend.

**Comment by carceneaux** [comment]
Checking this script you referenced, here's the code that covers that logic:

https://github.com/VeeamHub/powershell/blob/3bf8bff035b1c5ccbcce181b181089a0a8181b95/BR-DataIntegrationAPIAtScale/BR-DataIntegrationAPIModule.psm1#L37-L71

Per the code, before choosing a random server, the script looks for a target server where the number of active restore sessions does not exceed 2 sessions.

With this in mind, you can either adjust this logic in the script to what you desire or ensure your target server meets the requirements the script is looking for.
