### ISSUE TITLE
Connect-VB365RestorePortal.ps1 not working

### ISSUE THREAD

**Issue by sbeccato** [VeeamHub/powershell#189]
**Describe the bug**
The script "Connect-VB365RestorePortal.ps1" is not working. 

**To Reproduce**
1. Add the correct applicationID in the script and launch it
2. Login with credential with admin privileges
3. See error

**Expected behavior**
The script creates new service principal

**Screenshots**
![image](https://github.com/VeeamHub/powershell/assets/31409573/c485870d-9673-4fec-b06b-f67d44c110c4)

**Additional context**
The user used to login into Microsoft Organization has full privileges

**Comment by carceneaux** [comment]
Thanks @sbeccato for reporting this.

Can you please double-check that valid credentials are being used? Also, the Azure account leveraged must be assigned the _Global Administrator_ role ([reference documentation](https://helpcenter.veeam.com/docs/vbo365/guide/ad_app_permissions_sd.html?ver=70#required-user-account-roles-for-azure-ad-applications)).

The failure shown in the screenshot is occurring at the Microsoft login phase of the script indicating there's a problem with the credentials.

**Comment by carceneaux** [comment]
Thanks for the additional information. Permissions shouldn't be an issue and MFA should be supported as one of the M365 Organizations I used for testing had MFA enabled.

As the authentication method in the script uses Microsoft's cmdlets, have you tried authenticating manually?

Here's a link to the lines in the script where authentication to Microsoft is performed:

https://github.com/VeeamHub/powershell/blob/6a701a8560935e83df7cc845da33838209dddb12/VB365-RestorePortalSetup/Connect-VB365RestorePortal.ps1#L66C5-L71C99

**Comment by sbeccato** [comment]
Just tried, here the result:
![image](https://github.com/VeeamHub/powershell/assets/31409573/bdf44aac-7fff-4a73-b561-e491f8f4282e)
The login (first command) ended correctly, I got the error within the last command

**Comment by carceneaux** [comment]
That does appear to be the issue. Let me test this in my lab and I'll report back.

**Comment by sbeccato** [comment]
Hi @carceneaux ,
I tried to use "Connect-AzureAD" directly instead "Connect-AzAccount" + "Connect-AzureAD" and seems to work.
In this case there is also to fix the line #97.

Hope this cal help

**Comment by carceneaux** [comment]
@sbeccato Unfortunately, I'm unable to duplicate this behavior. I performed the below work this morning with no issues.

![CleanShot 2023-10-18 at 08 14 42@2x](https://github.com/VeeamHub/powershell/assets/17179966/8ea06e6c-39ba-4a74-9b86-a013ccf5fdb5)

I did notice in your screenshots that it looks like you're running an out of date PowerShell module. Have you tried updating it?

Here's the versions I'm currently running. Which versions are you running?

<img width="269" alt="CleanShot 2023-10-18 at 08 17 36@2x" src="https://github.com/VeeamHub/powershell/assets/17179966/732f9963-ac98-4944-acfb-d39bbd179315">

**Comment by carceneaux** [comment]
Ok, that makes sense. So an updated module has disabled the method of authentication I'm using.

**Background info:** I chose this method of auth to avoid having to request authentication two times in a row.

I'll test using the updated modules and see if there's a workaround.

**Comment by sbeccato** [comment]
Hi @carceneaux , do you have any update on this?

**Comment by carceneaux** [comment]
Sorry for the delay as this had to tested. I've confirmed this behavior is caused by the AzureAD module version **2.0.2.180**. Using the newest stable version of the module (**2.0.2.182**), I did not see the error.

Please test the script [located here](https://raw.githubusercontent.com/VeeamHub/powershell/b1d6f25b56aa43824e3521d43e6cd010e049bd50/VB365-RestorePortalSetup/Connect-VB365RestorePortal.ps1) and let me know.

Essentially, I added code to check AzureAD module version and to upgrade it if necessary.

**Comment by sbeccato** [comment]
Hi @carceneaux ,
tested just now, works as expected (login is requested twice but is not a problem).

Thank you!
