### ISSUE TITLE
Formatting Issue on Job Policy

### ISSUE THREAD

**Issue by dgroeschen** [VeeamHub/powershell#199]
**Describe the bug**
The output html file does not properly display the policy name when spacing or dashes appear in the policy name. This does not appear to affect policy names with underscores in them. 

**To Reproduce**
1. Create Policy Name "Example - Test Backup" 
2. Run Backup
3. Run BR-Morning Report
4. See Policy name in report only shows "Example" 

**Expected behavior**
The output should have the correct Policy name listed next to the machine

**Screenshots**

**Veeam (please complete the following information):**
 - OS: Windows Server 2022
 - Browser N/A
 - Version v12 0713 

**Additional context**

**Comment by cevans3505** [comment]
@dgroeschen I'm not the original author of this script, but I believe I see where the issue is in the code. If you would be willing to share at least a screenshot illustrating what you're referring to exactly, I can likely fix this rather easily.
