### ISSUE TITLE
VB365-ExportMailboxToPST fails at message total+1

### ISSUE THREAD

**Issue by peoyli** [VeeamHub/powershell#209]
@chris_arceneaux

Is this the expected behavior ?
==
Export-UserMailbox.ps1
-----------------------

 Export Exchange Items Session
    Processing 101 out of 21174 items...
    ...

Then at the end:
...
Exporting mailbox: (Not Realname - not.realname@notrealdomain.com) to s:\restore\notreal.pst	
C:\Scripts\Export-UserMailbox.ps1 : Error encountered. Stopping restore session.
The value 21175 must be in the range from 0 to 21174.
Parameter name: value
At line:1 char:1
+ C:\Scripts\Export-UserMailbox.ps1
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Export-UserMailbox.ps1

==
Should I trust the created .pst even if it fails at the end ?

**Comment by carceneaux** [comment]
As the export failed, the PST file will not include all items that were meant to be exported.

To troubleshoot, I recommend exporting the mailbox using [Veeam Explorers](https://helpcenter.veeam.com/docs/vbo365/explorers/vex_export_custom.html?ver=70). If the problem still persists, I recommend opening a case with Veeam support.
