### ISSUE TITLE
Doesn't pickup VMs or Hosts from failover plan

### ISSUE THREAD

**Issue by ZaphodJustSomeGuy** [VeeamHub/powershell#60]
Hi there

I tried your script today for linux replica re-ip, and found some issues against our environment.

The first one is because we add VMs to the Veeam failover plan using the "VMs and Templates" picker rather than by "Tag" or "Hosts and Clusters" view, your Get-VBRFailoverPlanVMs command doesn't find any VMs.

After adding the VMs via the "Hosts and Clusters" view instead, it gets further but doesn't return a valid parent host ID, as it seems to be looking for DNS name, and our servers are added to vCenter via IP only (no local DNS was available when building this cluster).

Is it possible to account for these 2 possibilities above in your scripts?

Thanks in advance.

**Comment by ZaphodJustSomeGuy** [comment]
So I managed to edit the script to swap-out "HostsAndClusters" with "VMsAndTemplates" in order for it to find VMs added to the replication jobs from that view, but it didn't look easy to modify it to check both (since the type would equal "Virtual Machine" in both views).

Also by changing .DnsName to Name it was able to find the host for each VM via it's IP address.

Still hoping that Veeam actually add proper Linux re-ip support as there doesn't seem to be a way to reset the IP if you fail-back, replicating the changes made at the DR site back to Live.

**Comment by carceneaux** [comment]
Closing this issue as significant time has passed. Feel free to re-open if you are still having this issue.

In the future, please reference the exact script that's being referred to in this repository...there are lots. 😄

**Comment by jhoughes** [comment]
For the sake of history, this was referencing the module & scripts within the 'BR-UpdateReplicaIP' folder.
