### ISSUE TITLE
using configure_veeam.ps1 to restore from object storage

### ISSUE THREAD

**Issue by uhassaninjss** [VeeamHub/powershell#66]
Please if anyone used this script (configure_veeam.ps1) to restore from object storage
please send me the steps
Thanks

**Comment by dipstar** [comment]
@uhassaninjss This is not the place for requests such as these. 

Unless you are experiencing issues with the script, then please post what the issue is and how it can be reproduced

**Comment by nielsengelen** [comment]
This script is used for the initial setup of a VBR server. You can’t restore from object storage with this script.

**Comment by uhassaninjss** [comment]
I'm asking because the author used this script to rebuild the repository from the Object storage backup
he mentioned in this link https://anthonyspiteri.net/disaster-recovery-and-resiliency-with-veeam-cloud-tier/#prettyPhoto
please forward to video to 32:00

**Comment by uhassaninjss** [comment]
> @uhassaninjss This is not the place for requests such as these.
> 
> Unless you are experiencing issues with the script, then please post what the issue is and how it can be reproduced

sorry if I miss placed it

**Comment by jhoughes** [comment]
@uhassaninjss, this script is not intended to restore from object storage, but to configure a Veeam environment.

Anthony's CFD video shows how you could use this same configuration script to reconnect to those previously used components after some catastrophic failure and "rebuilding" from a clean Veeam installation.

This script is intended to build (or rebuild as in Anthony's demo) a functioning Veeam environment and you would run it as described in the README.  You must populate all of your configuration variables into the config.json file prior to running the script, as all of the configuration details are pulled from that file.

If you are trying to duplicate the results that Anthony had in the CFD video, you would run the script against a new Veeam installation with the same config.json configuration file which was used to build the environment the first time.

If you did not build the environment initially via this method, then you would need to put your configuration parameters into the config.json file first, then run the script against a new Veeam installation.
